# ──────────────────────────────────────────────────────────────
# tell Netlify how to build & publish your Vite app:
[build]
  command   = "npm run build"    # or "yarn build" if you use yarn
  publish   = "dist"             # Vite’s default output folder
# ──────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────
# Redirect any "/Something" to "/subject/Something" at 200 (proxy)
# (so the URL stays clean, but Netlify serves your existing pages)
[[redirects]]
  from     = "/:subject"
  to       = "/subject/:subject"
  status   = 200
  force    = true
# ──────────────────────────────────────────────────────────────
