import { Formula } from './types';

// Get initial formula data
export function getInitialFormulas(): Formula[] {
  return [
    // Mathematics Formulas
    {
      id: 'math-quad-1',
      title: 'Quadratic Formula',
      formula: 'x = (-b ± √(b² - 4ac)) / 2a',
      explanation: 'For a quadratic equation ax² + bx + c = 0, this formula gives the values of x that solve the equation.',
      subject: 'Maths',
      chapter: 'Quadratic Equations',
      important: true,
      latex: 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}'
    },
    {
      id: 'math-deriv-1',
      title: 'Power Rule',
      formula: 'd/dx [xⁿ] = n·xⁿ⁻¹',
      explanation: 'The derivative of x raised to the power n is n times x raised to the power (n-1).',
      subject: 'Maths',
      chapter: 'Differentiation',
      important: true,
      latex: '\\frac{d}{dx}[x^n] = n \\cdot x^{n-1}'
    },
    {
      id: 'math-integ-1',
      title: 'Power Rule Integration',
      formula: '∫ xⁿ dx = xⁿ⁺¹/(n+1) + C for n ≠ -1',
      explanation: 'The integral of x raised to the power n is x raised to the power (n+1) divided by (n+1), plus a constant.',
      subject: 'Maths',
      chapter: 'Integration',
      important: true,
      latex: '\\int x^n dx = \\frac{x^{n+1}}{n+1} + C \\text{ for } n \\neq -1'
    },
    {
      id: 'math-trig-1',
      title: 'Pythagorean Identity',
      formula: 'sin²θ + cos²θ = 1',
      explanation: 'The fundamental trigonometric identity relating sine and cosine functions.',
      subject: 'Maths',
      chapter: 'Trigonometry',
      important: true,
      latex: '\\sin^2\\theta + \\cos^2\\theta = 1'
    },
    {
      id: 'math-complex-1',
      title: 'Euler\'s Formula',
      formula: 'e^(iθ) = cos θ + i sin θ',
      explanation: 'Relates complex exponentials to trigonometric functions.',
      subject: 'Maths',
      chapter: 'Complex Numbers',
      important: true,
      latex: 'e^{i\\theta} = \\cos \\theta + i \\sin \\theta'
    },
    {
      id: 'math-vectors-1',
      title: 'Dot Product',
      formula: 'A·B = |A||B|cosθ',
      explanation: 'The dot product of two vectors A and B is the product of their magnitudes and the cosine of the angle between them.',
      subject: 'Maths',
      chapter: 'Vectors',
      important: true,
    },
    {
      id: 'math-vectors-2',
      title: 'Cross Product Magnitude',
      formula: '|A×B| = |A||B|sinθ',
      explanation: 'The magnitude of the cross product of two vectors A and B is the product of their magnitudes and the sine of the angle between them.',
      subject: 'Maths',
      chapter: 'Vectors',
      important: false,
    },
    {
      id: 'math-probability-1',
      title: 'Binomial Probability',
      formula: 'P(X=k) = ₙCₖ p^k (1-p)^(n-k)',
      explanation: 'The probability of exactly k successes in n independent Bernoulli trials with probability of success p.',
      subject: 'Maths',
      chapter: 'Probability',
      important: true,
    },
    {
      id: 'math-coordinate-1',
      title: 'Distance Formula',
      formula: 'd = √[(x₂-x₁)² + (y₂-y₁)²]',
      explanation: 'The distance between two points (x₁,y₁) and (x₂,y₂) in a Cartesian coordinate system.',
      subject: 'Maths',
      chapter: 'Coordinate Geometry',
      important: true,
    },
    {
      id: 'math-trigonometry-1',
      title: 'Law of Sines',
      formula: 'a/sin(A) = b/sin(B) = c/sin(C)',
      explanation: 'In any triangle, the ratio of the length of a side to the sine of the opposite angle is constant.',
      subject: 'Maths',
      chapter: 'Trigonometry',
      important: true,
    },
    
    // Physics Formulas
    {
      id: 'physics-mechanics-1',
      title: 'Newton\'s Second Law',
      formula: 'F = ma',
      explanation: 'The force acting on an object is equal to the mass of the object times its acceleration.',
      subject: 'Physics',
      chapter: 'Laws of Motion',
      important: true,
      latex: 'F = ma'
    },
    {
      id: 'physics-mechanics-2',
      title: 'Kinetic Energy',
      formula: 'KE = (1/2)mv²',
      explanation: 'The energy possessed by an object due to its motion.',
      subject: 'Physics',
      chapter: 'Work & Energy',
      important: true,
      latex: 'KE = \\frac{1}{2}mv^2'
    },
    {
      id: 'physics-em-1',
      title: 'Coulomb\'s Law',
      formula: 'F = k·q₁·q₂/r²',
      explanation: 'The electrostatic force between two charged particles.',
      subject: 'Physics',
      chapter: 'Electrostatics',
      important: true,
      latex: 'F = k\\frac{q_1 q_2}{r^2}'
    },
    {
      id: 'physics-optics-1',
      title: 'Snell\'s Law',
      formula: 'n₁sin(θ₁) = n₂sin(θ₂)',
      explanation: 'Relates the angles of incidence and refraction for light passing through different media.',
      subject: 'Physics',
      chapter: 'Ray Optics',
      important: true,
      latex: 'n_1\\sin(\\theta_1) = n_2\\sin(\\theta_2)'
    },
    {
      id: 'physics-modern-1',
      title: 'Energy-Mass Equivalence',
      formula: 'E = mc²',
      explanation: 'The energy equivalent of a mass m is equal to the mass times the square of the speed of light.',
      subject: 'Physics',
      chapter: 'Modern Physics',
      important: true,
      latex: 'E = mc^2'
    },
    {
      id: 'physics-mechanics-3',
      title: 'Momentum',
      formula: 'p = mv',
      explanation: 'Linear momentum is the product of an object\'s mass and velocity.',
      subject: 'Physics',
      chapter: 'Laws of Motion',
      important: true,
    },
    {
      id: 'physics-rotational-1',
      title: 'Rotational Kinetic Energy',
      formula: 'KE = (1/2)Iω²',
      explanation: 'The kinetic energy of a rotating object with moment of inertia I and angular velocity ω.',
      subject: 'Physics',
      chapter: 'Rotational Motion',
      important: false,
    },
    {
      id: 'physics-thermo-1',
      title: 'First Law of Thermodynamics',
      formula: 'ΔU = Q - W',
      explanation: 'The change in internal energy of a system equals the heat added to the system minus the work done by the system.',
      subject: 'Physics',
      chapter: 'Thermodynamics',
      important: true,
    },
    {
      id: 'physics-waves-1',
      title: 'Wave Speed',
      formula: 'v = fλ',
      explanation: 'The speed of a wave equals its frequency times its wavelength.',
      subject: 'Physics',
      chapter: 'Waves',
      important: true,
    },
    {
      id: 'physics-electricity-1',
      title: 'Ohm\'s Law',
      formula: 'V = IR',
      explanation: 'The voltage across a conductor is directly proportional to the current flowing through it.',
      subject: 'Physics',
      chapter: 'Current Electricity',
      important: true,
    },
    
    // Chemistry Formulas
    {
      id: 'chem-thermo-1',
      title: 'Gibbs Free Energy',
      formula: 'ΔG = ΔH - TΔS',
      explanation: 'The change in Gibbs free energy equals the change in enthalpy minus the product of temperature and change in entropy.',
      subject: 'Chemistry',
      chapter: 'Thermodynamics',
      important: true,
      latex: '\\Delta G = \\Delta H - T\\Delta S'
    },
    {
      id: 'chem-kinetics-1',
      title: 'Arrhenius Equation',
      formula: 'k = A·e^(-Ea/RT)',
      explanation: 'Describes the temperature dependence of reaction rates.',
      subject: 'Chemistry',
      chapter: 'Chemical Kinetics',
      important: true,
      latex: 'k = A \\cdot e^{-E_a/RT}'
    },
    {
      id: 'chem-equil-1',
      title: 'Equilibrium Constant',
      formula: 'K = [products]/[reactants]',
      explanation: 'The ratio of product concentrations to reactant concentrations at equilibrium, each raised to their stoichiometric coefficients.',
      subject: 'Chemistry',
      chapter: 'Chemical Equilibrium',
      important: true,
      latex: 'K = \\frac{[\\text{products}]}{[\\text{reactants}]}'
    },
    {
      id: 'chem-ph-1',
      title: 'pH Definition',
      formula: 'pH = -log[H⁺]',
      explanation: 'The negative logarithm of the hydrogen ion concentration.',
      subject: 'Chemistry',
      chapter: 'Chemical Equilibrium',
      important: true,
      latex: 'pH = -\\log[H^+]'
    },
    {
      id: 'chem-redox-1',
      title: 'Nernst Equation',
      formula: 'E = E° - (RT/nF)·ln(Q)',
      explanation: 'Relates the reduction potential of a cell to the standard reduction potential and reaction quotient.',
      subject: 'Chemistry',
      chapter: 'Redox Reactions',
      important: true,
      latex: 'E = E^\\circ - \\frac{RT}{nF}\\ln(Q)'
    },
    {
      id: 'chem-gas-1',
      title: 'Ideal Gas Law',
      formula: 'PV = nRT',
      explanation: 'Relates pressure, volume, amount of substance, and temperature for an ideal gas.',
      subject: 'Chemistry',
      chapter: 'Gaseous State',
      important: true,
    },
    {
      id: 'chem-atomic-1',
      title: 'de Broglie Wavelength',
      formula: 'λ = h/mv',
      explanation: 'The wavelength associated with a particle of mass m and velocity v.',
      subject: 'Chemistry',
      chapter: 'Atomic Structure',
      important: false,
    },
    {
      id: 'chem-solution-1',
      title: 'Raoult\'s Law',
      formula: 'P = X·P°',
      explanation: 'The partial pressure of a component in a solution equals its mole fraction times its vapor pressure in pure form.',
      subject: 'Chemistry',
      chapter: 'Solutions',
      important: false,
    },
    {
      id: 'chem-organic-1',
      title: 'Rate Law',
      formula: 'Rate = k[A]ᵐ[B]ⁿ',
      explanation: 'The rate of a reaction equals the rate constant k times the concentrations of reactants raised to their orders.',
      subject: 'Chemistry',
      chapter: 'Chemical Kinetics',
      important: true,
    },
    {
      id: 'chem-colligative-1',
      title: 'Molality',
      formula: 'm = moles of solute / kg of solvent',
      explanation: 'The concentration of a solution expressed as moles of solute per kilogram of solvent.',
      subject: 'Chemistry',
      chapter: 'Solutions',
      important: true,
    },
  ];
}
