// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxhgelqpyqmatofcfjjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4aGdlbHFweXFtYXRvZmNmampiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDc4NzYsImV4cCI6MjA1OTc4Mzg3Nn0.qy83Ew0yVZzhZ6aOH2BEJIovg5lI3ewGncBcFv3SlE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);